version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: wifi_user
      POSTGRES_PASSWORD: wifi_pass
      POSTGRES_DB: wifi_db
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U wifi_user -d wifi_db']
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://wifi_user:wifi_pass@db:5432/wifi_db
      CSV_FILE: app/puntos_wifi_cdmx.csv
    ports:
      - '8000:8000'
    command: bash -c "python app/init_db.py && uvicorn app.main:app --host 0.0.0.0 --port 8000"

  tests:
    build: .
    depends_on:
      db:
        condition: service_healthy
      app:
        condition: service_started
    environment:
      DATABASE_URL: postgresql+asyncpg://wifi_user:wifi_pass@db:5432/wifi_db
    command: pytest -v --tb=short # Ejecutar pytest con resumen
    volumes:
      - .:/app # Montar el directorio actual en /app

volumes:
  db_data:
